table_headers = [
    "People",
    "Indigenous status",
    "Age",
    "Registered marital status",
    "Social marital status",
    "Type of educational institution attending",
    "Level of highest educational attainment",
    "Ancestry, top responses",
    "Country of birth, top responses",
    "Country of birth of parents",
    "Country of birth of father, top stated responses",
    "Country of birth of mother, top stated responses",
    "Religious affiliation, top responses",
    "Language used at home, top responses (other than English)",
    "Participation in the labour force",
    "Employment status",
    "Employment, hours worked",
    "Occupation, top responses",
    "Industry of employment, top responses",
    "Median weekly incomes (a)",
    "Method of travel to work on the day of the Census, top responses",
    "Unpaid work and care",
    "Unpaid domestic work, number of hours",
    "Type of long-term health condition",
    "Count of selected long-term health conditions",
    "Australian Defence Force Service",
    "Family composition",
    "Single (or lone) parents",
    "Employment status of couple families",
    "Dwelling count",
    "Dwelling structure",
    "Number of bedrooms",
    "Number of registered motor vehicles",
    "Household composition",
    "Tenure type",
    "Household income",
    "Rent weekly payments",
    "Mortgage monthly repayments",
    "People characteristics",
    "Dwelling characteristics",
    "Mortgage and rent",
]

row_headers = [
    "Male",
    "Female",
    "Aboriginal and/or Torres Strait Islander",
    "Non-Indigenous",
    "Indigenous status not stated",
    "Median age",
    "0-4 years",
    "5-9 years",
    "10-14 years",
    "15-19 years",
    "20-24 years",
    "25-29 years",
    "30-34 years",
    "35-39 years",
    "40-44 years",
    "45-49 years",
    "50-54 years",
    "55-59 years",
    "60-64 years",
    "65-69 years",
    "70-74 years",
    "75-79 years",
    "80-84 years",
    "85 years and over",
    "Married",
    "Separated",
    "Divorced",
    "Widowed",
    "Never married",
    "Registered marriage (a)",
    "De facto marriage (b)",
    "Not married",
    "Preschool",
    "Primary - Government",
    "Primary - Catholic",
    "Primary - other non-Government",
    "Primary total (a)",
    "Secondary - Government",
    "Secondary - Catholic",
    "Secondary - other non-Government",
    "Secondary total (b)",
    "Tertiary - Vocational education (including TAFE and private training providers)",
    "Tertiary - University or other higher education",
    "Tertiary total (c)",
    "Other",
    "Not stated",
    "Bachelor Degree level and above",
    "Advanced Diploma and Diploma level",
    "Certificate level IV",
    "Certificate level III",
    "Year 12",
    "Year 11",
    "Year 10",
    "Certificate level II",
    "Certificate level I",
    "Year 9 or below",
    "Inadequately described",
    "No educational attainment",
    "Not stated",
    "English",
    "Australian",
    "Chinese",
    "Irish",
    "Scottish",
    "Australia",
    "China (excludes SARs and Taiwan)",
    "India",
    "England",
    "Malaysia",
    "Hong Kong (SAR of China)",
    "Both parents born overseas",
    "Father only born overseas",
    "Mother only born overseas",
    "Both parents born in Australia",
    "Not stated",
    "Australia",
    "China (excludes SARs and Taiwan)",
    "England",
    "India",
    "Malaysia",
    "Australia",
    "China (excludes SARs and Taiwan)",
    "India",
    "England",
    "Malaysia",
    "No Religion, so described",
    "Catholic",
    "Anglican",
    "Not stated",
    "Christian, nfd",
    "Mandarin",
    "Cantonese",
    "Vietnamese",
    "Italian",
    "Persian (excluding Dari)",
    "English only used at home",
    "Households where a non-English language is used",
    "In the labour force",
    "Not in the labour force",
    "Not stated",
    "Worked full-time",
    "Worked part-time",
    "Away from work (a)",
    "Unemployed",
    "0 hours (away from work)",
    "1-19 hours",
    "20-29 hours",
    "30-34 hours",
    "35-39 hours",
    "40-44 hours",
    "45 hours or more",
    "Professionals",
    "Managers",
    "Clerical and Administrative Workers",
    "Technicians and Trades Workers",
    "Community and Personal Service Workers",
    "Sales Workers",
    "Labourers",
    "Machinery Operators and Drivers",
    "Hospitals (except Psychiatric Hospitals)",
    "Computer System Design and Related Services",
    "Banking",
    "Cafes and Restaurants",
    "Primary Education",
    "Personal (b)",
    "Family (c)",
    "Household (d)",
    "Car, as driver",
    "Train",
    "Car, as passenger",
    "Walked only",
    "Train, bus",
    "Did not go to work",
    "Worked at home",
    "People who travelled to work by public transport (a)",
    "People who travelled to work by car as driver or passenger (b)",
    "Did unpaid domestic work (week before Census Night)",
    "Provided unpaid care for child/children (during two weeks before Census Night)",
    "Provided unpaid assistance to a person with a disability, health condition or due to old age (during two weeks before Census Night)",
    "Did voluntary work through an organisation or group (last 12 months)",
    "Less than 5 hours",
    "5 to 14 hours",
    "15 to 29 hours",
    "30 hours or more",
    "Arthritis",
    "Asthma",
    "Cancer (including remission)",
    "Dementia (including Alzheimer's)",
    "Diabetes (excluding gestational diabetes)",
    "Heart disease (including heart attack or angina)",
    "Kidney disease",
    "Lung condition (including COPD or emphysema)",
    "Mental health condition (including depression or anxiety)",
    "Stroke",
    "Any other long-term health condition(s)",
    "No long-term health condition(s)",
    "Not stated",
    "None of the selected conditions",
    "One condition",
    "Two conditions",
    "Three or more conditions",
    "Not stated",
    "Currently serving",
    "Previously served (and not currently serving)",
    "Has never served",
    "Not stated",
    "Couple family without children",
    "Couple family with children",
    "One parent family",
    "Other family",
    "Male",
    "Female",
    "Both employed, worked full-time",
    "Both employed, worked part-time",
    "One employed full-time, one part-time",
    "One employed full-time, other not working",
    "One employed part-time, other not working",
    "Both not working",
    "Other",
    "Labour force status not stated",
    "Occupied private dwellings",
    "Unoccupied private dwellings",
    "Separate house",
    "Semi-detached, row or terrace house, townhouse etc",
    "Flat or apartment",
    "Other dwelling",
    "None (includes studio apartments or bedsitters)",
    "1 bedroom",
    "2 bedrooms",
    "3 bedrooms",
    "4 or more bedrooms",
    "Number of bedrooms not stated",
    "Average number of bedrooms per dwelling",
    "Average number of people per household",
    "None",
    "1 motor vehicle",
    "2 motor vehicles",
    "3 or more vehicles",
    "Number of motor vehicles not stated",
    "Family households",
    "Single (or lone) person households",
    "Group households",
    "Owned outright",
    "Owned with a mortgage (a)",
    "Rented (b)",
    "Other tenure type (c)",
    "Tenure type not stated",
    "Less than $650 total household weekly income (a)",
    "More than $3,000 total household weekly income (a)",
    "Median rent (a)",
    "Renter households where rent payments are less than or equal to 30% of household income (b)",
    "Renter households with rent payments greater than 30% of household income (b)",
    "Unable to determine (c)",
    "Median mortgage repayments",
    "Owner with mortgage households where mortgage repayments are less than or equal to 30% of household income (a)",
    "Owner with mortgage households with mortgage repayments greater than 30% of household income (a)",
    "Unable to determine (b)",
    "Male",
    "Female",
    "Median age",
    "Average number of people per household",
    "Average number of people per bedroom",
    "Median weekly household income (a)",
    "Median weekly rent (a)",
    "Median monthly mortgage repayments",
]
